services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: finmentor_backend

    env_file:
      - ./backend/.env

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: finmentor_frontend

    ports:
      - "3000:80"

    depends_on:
      - backend