import type {
  LearningPath,
  Course,
  ResourceItem,
  DailyChallenge,
  Badge,
  Certificate,
  LearningUserStats,
  LeaderboardUser,
} from '../types/learning';

/* ── 1. User Stats & Progress ───────────────────────────────── */
export const MOCK_USER_STATS: LearningUserStats = {
  level: 8,
  levelTitle: 'Financial Strategist',
  currentXp: 3450,
  nextLevelXp: 5000,
  streakDays: 14,
  coursesCompleted: 4,
  certificatesEarned: 2,
  hoursLearned: 28.5,
  quizAccuracyPercentage: 88,
  todayGoalMinutes: 30,
  todayCompletedMinutes: 20,
  strongTopics: ['Emergency Funds', '50/30/20 Budgeting', 'SIP Compounding', 'Tax Deductions'],
  weakTopics: ['Options & Futures', 'Direct Stock Valuation', 'Asset Rebalancing'],
  heatmap: Array.from({ length: 90 }, (_, i) => {
    const d = new Date();
    d.setDate(d.getDate() - (89 - i));
    const dateStr = d.toISOString().split('T')[0];
    const rand = Math.floor(Math.random() * 5);
    return {
      date: dateStr,
      count: rand,
      intensity: (rand > 3 ? 4 : rand > 2 ? 3 : rand > 1 ? 2 : rand > 0 ? 1 : 0) as 0 | 1 | 2 | 3 | 4,
    };
  }),
};

/* ── 2. All 15 Learning Paths ───────────────────────────────── */
export const LEARNING_PATHS: LearningPath[] = [
  {
    id: 'path-1',
    title: '1. Personal Finance Foundations',
    description: 'Master money mindsets, net worth calculations, cash flow mechanics, and financial discipline.',
    iconName: 'Compass',
    difficulty: 'Beginner',
    completionPercentage: 100,
    durationHours: 6,
    lessonsCount: 12,
    coursesCount: 2,
    hasCertificate: true,
    unlocked: true,
    category: 'Financial Psychology',
    gradient: 'from-blue-500/20 to-indigo-500/10',
    milestones: [
      { id: 'm1', title: 'Money Mindset & Financial Literacy', durationMinutes: 15, completed: true, type: 'lesson' },
      { id: 'm2', title: 'Calculating Net Worth vs Salary', durationMinutes: 20, completed: true, type: 'lesson' },
      { id: 'm3', title: 'Foundations Assessment', durationMinutes: 15, completed: true, type: 'quiz' },
    ],
  },
  {
    id: 'path-2',
    title: '2. Budgeting Mastery',
    description: 'Learn zero-based budgeting, 50/30/20 rule, tracking micro-expenses, and automating cash flows.',
    iconName: 'PieChart',
    difficulty: 'Beginner',
    completionPercentage: 75,
    durationHours: 8,
    lessonsCount: 16,
    coursesCount: 3,
    hasCertificate: true,
    unlocked: true,
    category: 'Budgeting',
    gradient: 'from-emerald-500/20 to-teal-500/10',
    milestones: [
      { id: 'm4', title: 'The 50/30/20 Golden Framework', durationMinutes: 20, completed: true, type: 'lesson' },
      { id: 'm5', title: 'Building Your Monthly System', durationMinutes: 25, completed: true, type: 'lesson' },
      { id: 'm6', title: 'Budgeting Master Quiz', durationMinutes: 15, completed: false, type: 'quiz' },
    ],
  },
  {
    id: 'path-3',
    title: '3. Smart Saving Strategies',
    description: 'Build high-yield savings habits, automate recurring deposits, and beat inflation effortlessly.',
    iconName: 'PiggyBank',
    difficulty: 'Beginner',
    completionPercentage: 40,
    durationHours: 5,
    lessonsCount: 10,
    coursesCount: 2,
    hasCertificate: true,
    unlocked: true,
    category: 'Saving',
    gradient: 'from-amber-500/20 to-orange-500/10',
    milestones: [
      { id: 'm7', title: 'High-Yield Savings vs Savings Accounts', durationMinutes: 15, completed: true, type: 'lesson' },
      { id: 'm8', title: 'Automating Monthly Savings Buckets', durationMinutes: 20, completed: false, type: 'lesson' },
    ],
  },
  {
    id: 'path-4',
    title: '4. Debt Management',
    description: 'Master the Debt Avalanche & Snowball strategies to eliminate high-interest liabilities fast.',
    iconName: 'ShieldAlert',
    difficulty: 'Intermediate',
    completionPercentage: 20,
    durationHours: 7,
    lessonsCount: 14,
    coursesCount: 2,
    hasCertificate: true,
    unlocked: true,
    category: 'Financial Planning',
    gradient: 'from-rose-500/20 to-pink-500/10',
    milestones: [
      { id: 'm9', title: 'Avalanche vs Snowball Method', durationMinutes: 25, completed: true, type: 'lesson' },
      { id: 'm10', title: 'Refinancing & Restructuring Loans', durationMinutes: 30, completed: false, type: 'lesson' },
    ],
  },
  {
    id: 'path-5',
    title: '5. Credit Score Essentials',
    description: 'Understand CIBIL/Experian mechanics, credit utilization ratios, and how to build a 780+ score.',
    iconName: 'CreditCard',
    difficulty: 'Beginner',
    completionPercentage: 0,
    durationHours: 4,
    lessonsCount: 8,
    coursesCount: 1,
    hasCertificate: false,
    unlocked: true,
    category: 'Financial Planning',
    gradient: 'from-violet-500/20 to-purple-500/10',
    milestones: [],
  },
  {
    id: 'path-6',
    title: '6. Emergency Fund Planning',
    description: 'Calculate 3-6 months liquid safety reserves and structure risk-free capital buffers.',
    iconName: 'LifeBuoy',
    difficulty: 'Beginner',
    completionPercentage: 100,
    durationHours: 4,
    lessonsCount: 8,
    coursesCount: 1,
    hasCertificate: true,
    unlocked: true,
    category: 'Saving',
    gradient: 'from-cyan-500/20 to-blue-500/10',
    milestones: [],
  },
  {
    id: 'path-7',
    title: '7. Investing Fundamentals',
    description: 'De-mystify risk vs return, compounding power, asset allocation, and market cycles.',
    iconName: 'TrendingUp',
    difficulty: 'Intermediate',
    completionPercentage: 50,
    durationHours: 10,
    lessonsCount: 18,
    coursesCount: 3,
    hasCertificate: true,
    unlocked: true,
    category: 'Investing',
    gradient: 'from-blue-600/20 to-indigo-600/10',
    milestones: [],
  },
  {
    id: 'path-8',
    title: '8. Mutual Funds & Indexing',
    description: 'Direct vs Regular funds, SIP, SWP, Index Funds, Nifty 50, and Expense Ratio analysis.',
    iconName: 'Layers',
    difficulty: 'Intermediate',
    completionPercentage: 15,
    durationHours: 9,
    lessonsCount: 15,
    coursesCount: 2,
    hasCertificate: true,
    unlocked: true,
    category: 'Mutual Funds',
    gradient: 'from-teal-500/20 to-emerald-500/10',
    milestones: [],
  },
  {
    id: 'path-9',
    title: '9. Stock Market Basics',
    description: 'How stock exchanges operate, fundamentals of Balance Sheets, P/E ratios, and Market Cap.',
    iconName: 'BarChart2',
    difficulty: 'Intermediate',
    completionPercentage: 0,
    durationHours: 12,
    lessonsCount: 20,
    coursesCount: 4,
    hasCertificate: true,
    unlocked: true,
    category: 'Stock Market',
    gradient: 'from-amber-500/20 to-yellow-500/10',
    milestones: [],
  },
  {
    id: 'path-10',
    title: '10. Advanced Investing',
    description: 'Valuation models (DCF), Sectoral Rotation, Risk-Adjusted Returns (Sharpe Ratio), and Rebalancing.',
    iconName: 'Activity',
    difficulty: 'Advanced',
    completionPercentage: 0,
    durationHours: 15,
    lessonsCount: 24,
    coursesCount: 4,
    hasCertificate: true,
    unlocked: false,
    category: 'Investing',
    gradient: 'from-purple-600/20 to-pink-600/10',
    milestones: [],
  },
  {
    id: 'path-11',
    title: '11. Retirement Planning & FIRE',
    description: 'Calculate your FIRE number (Financial Independence, Retire Early) and NPS/EPF strategies.',
    iconName: 'Sunset',
    difficulty: 'Intermediate',
    completionPercentage: 0,
    durationHours: 8,
    lessonsCount: 14,
    coursesCount: 2,
    hasCertificate: true,
    unlocked: true,
    category: 'Financial Planning',
    gradient: 'from-orange-500/20 to-rose-500/10',
    milestones: [],
  },
  {
    id: 'path-12',
    title: '12. Tax Planning & Optimization',
    description: 'Old vs New Tax regime, Section 80C, 80D, LTCG vs STCG, and legitimate tax deduction tactics.',
    iconName: 'FileCheck',
    difficulty: 'Intermediate',
    completionPercentage: 10,
    durationHours: 8,
    lessonsCount: 12,
    coursesCount: 2,
    hasCertificate: true,
    unlocked: true,
    category: 'Taxes',
    gradient: 'from-indigo-500/20 to-blue-500/10',
    milestones: [],
  },
  {
    id: 'path-13',
    title: '13. Insurance Safeguards',
    description: 'Term Life Insurance vs Endowment plans, Health Insurance floaters, and top-up riders.',
    iconName: 'ShieldCheck',
    difficulty: 'Beginner',
    completionPercentage: 0,
    durationHours: 5,
    lessonsCount: 10,
    coursesCount: 1,
    hasCertificate: true,
    unlocked: true,
    category: 'Insurance',
    gradient: 'from-emerald-600/20 to-teal-600/10',
    milestones: [],
  },
  {
    id: 'path-14',
    title: '14. Wealth Building Blueprint',
    description: 'Multi-asset allocation, Real Estate, Gold sovereign bonds, and passive income engines.',
    iconName: 'Coins',
    difficulty: 'Advanced',
    completionPercentage: 0,
    durationHours: 14,
    lessonsCount: 22,
    coursesCount: 3,
    hasCertificate: true,
    unlocked: false,
    category: 'Passive Income',
    gradient: 'from-yellow-500/20 to-amber-600/10',
    milestones: [],
  },
  {
    id: 'path-15',
    title: '15. Financial Independence',
    description: 'Estate planning, generational wealth transmission, and living off 4% withdrawal rate.',
    iconName: 'Award',
    difficulty: 'Advanced',
    completionPercentage: 0,
    durationHours: 16,
    lessonsCount: 25,
    coursesCount: 3,
    hasCertificate: true,
    unlocked: false,
    category: 'Financial Planning',
    gradient: 'from-blue-600/20 to-purple-600/10',
    milestones: [],
  },
];

/* ── 3. Courses Data ────────────────────────────────────────── */
export const POPULAR_COURSES: Course[] = [
  {
    id: 'course-1',
    title: '50/30/20 Budgeting Masterclass',
    description: 'Transform your monthly paychecks into automated wealth engines with practical spreadsheets.',
    category: 'Budgeting',
    difficulty: 'Beginner',
    durationHours: 2.5,
    lessonsCount: 8,
    studentsEnrolled: 14200,
    rating: 4.9,
    progressPercentage: 75,
    bookmarked: true,
    thumbnailGradient: 'from-blue-600 to-indigo-700',
    iconName: 'PieChart',
    modules: [
      {
        id: 'm1',
        title: 'Module 1: The 50/30/20 Breakdown',
        lessons: [
          {
            id: 'l1',
            title: 'Understanding Needs vs Wants',
            durationMinutes: 12,
            completed: true,
            summary: 'Identify mandatory expenditures vs lifestyle desires to prevent budget leaks.',
            keyTakeaways: ['Needs = Housing, Utilities, Basic Groceries', 'Wants = Dining out, Subscriptions', 'Savings = 20% minimum target'],
          },
          {
            id: 'l2',
            title: 'Setting Up Your Bank Buckets',
            durationMinutes: 18,
            completed: true,
            summary: 'Organize three dedicated accounts to automate budget allocations on payday.',
            keyTakeaways: ['Primary income account', 'Fixed needs account', 'Flexible wants debit card'],
          },
        ],
      },
    ],
  },
  {
    id: 'course-2',
    title: 'SIP & Mutual Funds Decoded',
    description: 'Learn how to pick top-performing index & equity mutual funds with low expense ratios.',
    category: 'Mutual Funds',
    difficulty: 'Intermediate',
    durationHours: 4.0,
    lessonsCount: 12,
    studentsEnrolled: 18900,
    rating: 4.95,
    progressPercentage: 45,
    bookmarked: true,
    thumbnailGradient: 'from-teal-600 to-emerald-700',
    iconName: 'TrendingUp',
    modules: [],
  },
  {
    id: 'course-3',
    title: 'Emergency Fund Blueprint',
    description: 'Never worry about sudden job loss or medical emergencies by building a 6-month buffer.',
    category: 'Saving',
    difficulty: 'Beginner',
    durationHours: 1.8,
    lessonsCount: 6,
    studentsEnrolled: 9800,
    rating: 4.85,
    progressPercentage: 100,
    bookmarked: false,
    thumbnailGradient: 'from-amber-600 to-orange-700',
    iconName: 'ShieldCheck',
    modules: [],
  },
  {
    id: 'course-4',
    title: 'Tax Savings Under Section 80C & 80D',
    description: 'Save up to ₹46,800 in annual taxes using ELSS, PPF, NPS, and Health Insurance exemptions.',
    category: 'Taxes',
    difficulty: 'Intermediate',
    durationHours: 3.2,
    lessonsCount: 10,
    studentsEnrolled: 22400,
    rating: 4.88,
    progressPercentage: 20,
    bookmarked: true,
    thumbnailGradient: 'from-purple-600 to-indigo-800',
    iconName: 'FileText',
    modules: [],
  },
  {
    id: 'course-5',
    title: 'Stock Market Fundamentals for Beginners',
    description: 'Read financial statements, understand P/E ratio, Market Cap, and avoid common investor traps.',
    category: 'Stock Market',
    difficulty: 'Intermediate',
    durationHours: 5.5,
    lessonsCount: 16,
    studentsEnrolled: 31000,
    rating: 4.92,
    progressPercentage: 0,
    bookmarked: false,
    thumbnailGradient: 'from-blue-700 to-cyan-800',
    iconName: 'BarChart2',
    modules: [],
  },
  {
    id: 'course-6',
    title: 'Term Insurance vs Life Policies',
    description: 'Why you should never mix investment with insurance. How to get ₹1 Crore term cover cheaply.',
    category: 'Insurance',
    difficulty: 'Beginner',
    durationHours: 2.0,
    lessonsCount: 7,
    studentsEnrolled: 8100,
    rating: 4.8,
    progressPercentage: 0,
    bookmarked: false,
    thumbnailGradient: 'from-rose-600 to-pink-700',
    iconName: 'ShieldAlert',
    modules: [],
  },
];

/* ── 4. Digital Library Resources ────────────────────────────── */
export const LIBRARY_RESOURCES: ResourceItem[] = [
  {
    id: 'res-1',
    title: 'The Psychology of Money',
    authorOrSource: 'Morgan Housel',
    type: 'Book',
    difficulty: 'Beginner',
    readingTimeMinutes: 180,
    coverGradient: 'from-slate-800 to-slate-900',
    tagline: 'Timeless lessons on wealth, greed, and happiness.',
    summary: 'Doing well with money has a little to do with how smart you are and a lot to do with how you behave.',
    bookmarked: true,
  },
  {
    id: 'res-2',
    title: 'Rich Dad Poor Dad',
    authorOrSource: 'Robert T. Kiyosaki',
    type: 'Book',
    difficulty: 'Beginner',
    readingTimeMinutes: 160,
    coverGradient: 'from-violet-800 to-purple-900',
    tagline: 'What the rich teach their kids about money that the poor and middle class do not!',
    summary: 'Assets put money in your pocket; liabilities take money out.',
    bookmarked: true,
  },
  {
    id: 'res-3',
    title: 'The Intelligent Investor Summary',
    authorOrSource: 'Benjamin Graham',
    type: 'Book',
    difficulty: 'Advanced',
    readingTimeMinutes: 240,
    coverGradient: 'from-blue-900 to-indigo-950',
    tagline: 'The definitive book on value investing.',
    summary: 'Margin of safety is the cornerstone of intelligent value investing.',
    bookmarked: false,
  },
  {
    id: 'res-4',
    title: '50/30/20 Excel Budget Template',
    authorOrSource: 'FinMentor AI Team',
    type: 'Template',
    difficulty: 'Beginner',
    readingTimeMinutes: 10,
    coverGradient: 'from-emerald-700 to-teal-800',
    tagline: 'Pre-formatted spreadsheet with automated expense charts.',
    summary: 'Plug in your income and expenses to automatically track needs, wants, and savings.',
    bookmarked: true,
  },
  {
    id: 'res-5',
    title: 'SIP Compound Interest Calculator Sheet',
    authorOrSource: 'FinMentor AI Team',
    type: 'Calculator',
    difficulty: 'Beginner',
    readingTimeMinutes: 5,
    coverGradient: 'from-cyan-700 to-blue-800',
    tagline: 'See the power of 15% CAGR over 10, 20, and 30 years.',
    summary: 'Interactive calculator displaying month-by-month wealth trajectory.',
    bookmarked: false,
  },
  {
    id: 'res-6',
    title: 'Old vs New Tax Regime Guide (2026)',
    authorOrSource: 'FinMentor Tax Desk',
    type: 'Guide',
    difficulty: 'Intermediate',
    readingTimeMinutes: 15,
    coverGradient: 'from-purple-800 to-indigo-900',
    tagline: 'Which regime saves you maximum tax based on your bracket?',
    summary: 'Side-by-side comparison tables with real salary calculations.',
    bookmarked: true,
  },
];

/* ── 5. Daily Challenges ────────────────────────────────────── */
export const DAILY_CHALLENGES: DailyChallenge[] = [
  {
    id: 'ch-1',
    title: 'Log Today\'s Micro Expenses',
    description: 'Enter every purchase made today into your Expense Tracker module.',
    xpReward: 100,
    coinReward: 25,
    completed: true,
    category: 'Budgeting',
    expiresInHours: 8,
  },
  {
    id: 'ch-2',
    title: 'Complete 1 Lesson in Budgeting Mastery',
    description: 'Watch or read 1 lesson in your active path today.',
    xpReward: 150,
    coinReward: 40,
    completed: false,
    category: 'Budgeting',
    expiresInHours: 8,
  },
  {
    id: 'ch-3',
    title: 'Take the Daily Financial Quiz',
    description: 'Score 80%+ on 5 quick multiple choice questions.',
    xpReward: 200,
    coinReward: 50,
    completed: false,
    category: 'Investing',
    expiresInHours: 8,
  },
];

/* ── 6. Badges & Achievements ───────────────────────────────── */
export const USER_BADGES: Badge[] = [
  {
    id: 'b-1',
    name: 'First Steps',
    description: 'Completed your first financial lesson',
    iconName: 'Award',
    unlocked: true,
    unlockedDate: 'July 15, 2026',
    category: 'Milestone',
  },
  {
    id: 'b-2',
    name: '7-Day Streak Warrior',
    description: 'Learned 7 consecutive days',
    iconName: 'Flame',
    unlocked: true,
    unlockedDate: 'July 22, 2026',
    category: 'Streak',
  },
  {
    id: 'b-3',
    name: 'Budget Master',
    description: 'Finished Personal Finance Foundations path',
    iconName: 'PieChart',
    unlocked: true,
    unlockedDate: 'July 25, 2026',
    category: 'Path Mastery',
  },
  {
    id: 'b-4',
    name: 'Tax Wizard',
    description: 'Score 100% on the Tax Planning Quiz',
    iconName: 'FileCheck',
    unlocked: false,
    category: 'Quiz',
  },
  {
    id: 'b-5',
    name: '30-Day Master',
    description: 'Maintain a 30-day learning streak',
    iconName: 'Zap',
    unlocked: false,
    category: 'Streak',
  },
];

/* ── 7. Certificates ────────────────────────────────────────── */
export const USER_CERTIFICATES: Certificate[] = [
  {
    id: 'cert-1',
    title: 'Certificate of Financial Foundations',
    issueDate: 'July 25, 2026',
    credentialId: 'FIN-CERT-2026-8891',
    pathId: 'path-1',
    skillsVerified: ['Net Worth Calculation', 'Cash Flow Analysis', 'Financial Goal Setting'],
  },
  {
    id: 'cert-2',
    title: 'Emergency Fund Master Certificate',
    issueDate: 'July 20, 2026',
    credentialId: 'FIN-CERT-2026-4412',
    pathId: 'path-6',
    skillsVerified: ['Liquidity Management', 'Emergency Reserve Planning', 'Risk Mitigation'],
  },
];

/* ── 8. Leaderboard ─────────────────────────────────────────── */
export const LEADERBOARD_USERS: LeaderboardUser[] = [
  { rank: 1, id: 'u-1', name: 'Aarav Sharma', xp: 9850, streak: 45, badgesCount: 14 },
  { rank: 2, id: 'u-2', name: 'Priya Patel', xp: 8720, streak: 32, badgesCount: 11 },
  { rank: 3, id: 'u-3', name: 'Rohan Verma', xp: 7900, streak: 28, badgesCount: 9 },
  { rank: 4, id: 'u-4', name: 'Yashwanth (You)', xp: 3450, streak: 14, badgesCount: 3, isCurrentUser: true },
  { rank: 5, id: 'u-5', name: 'Ananya Iyer', xp: 3100, streak: 12, badgesCount: 4 },
  { rank: 6, id: 'u-6', name: 'Vikram Singh', xp: 2850, streak: 9, badgesCount: 3 },
  { rank: 7, id: 'u-7', name: 'Sneha Reddy', xp: 2400, streak: 6, badgesCount: 2 },
];
