import { GraduationCap, Bot, PieChart, Receipt, Target, TrendingUp, BarChart3, BookOpen, Trophy, FileText, User, Settings, } from 'lucide-react';
export const APP_MODULES = [
    {
        id: 'learning',
        title: 'Learning Platform',
        description: 'Master personal finance with curated courses and quizzes',
        icon: GraduationCap,
        route: '/learn',
        gradient: 'from-blue-500/20 via-indigo-500/10 to-transparent',
        iconBg: 'from-blue-500 to-indigo-600',
        badge: 'Course',
        activity: 'Continue your last lesson',
        progressLabel: 'Finance Basics',
    },
    {
        id: 'ai-mentor',
        title: 'AI Financial Mentor',
        description: 'Get personalised coaching, insights and concept explanations',
        icon: Bot,
        route: '/ai',
        gradient: 'from-violet-500/20 via-purple-500/10 to-transparent',
        iconBg: 'from-violet-500 to-purple-600',
        badge: 'AI',
        activity: 'Ask about budgeting strategies',
        progressLabel: 'Always available',
    },
    {
        id: 'budget',
        title: 'Budget Planner',
        description: 'Build your 50/30/20 budget and track spending categories',
        icon: PieChart,
        route: '/budgets',
        gradient: 'from-emerald-500/20 via-teal-500/10 to-transparent',
        iconBg: 'from-emerald-500 to-teal-600',
        activity: 'Budget analysis updated',
        progressLabel: 'On track this month',
    },
    {
        id: 'expenses',
        title: 'Expense Tracker',
        description: 'Log, categorise and review every transaction',
        icon: Receipt,
        route: '/transactions',
        gradient: 'from-amber-500/20 via-orange-500/10 to-transparent',
        iconBg: 'from-amber-500 to-orange-500',
        activity: 'Last entry: 2 hours ago',
        progressLabel: 'Track every rupee',
    },
    {
        id: 'goals',
        title: 'Financial Goals',
        description: 'Set savings milestones and watch your progress grow',
        icon: Target,
        route: '/savings',
        gradient: 'from-rose-500/20 via-pink-500/10 to-transparent',
        iconBg: 'from-rose-500 to-pink-600',
        activity: 'Emergency fund in progress',
        progressLabel: 'Active goals',
    },
    {
        id: 'investments',
        title: 'Investments',
        description: 'Explore SIP, mutual funds and portfolio allocation',
        icon: TrendingUp,
        route: '/dashboard/investments',
        gradient: 'from-cyan-500/20 via-blue-500/10 to-transparent',
        iconBg: 'from-cyan-500 to-blue-500',
        badge: 'Soon',
        activity: 'Learn about SIP compounding',
        progressLabel: 'Grow your wealth',
    },
    {
        id: 'analytics',
        title: 'Analytics',
        description: 'Deep-dive into trends, ratios and financial health scores',
        icon: BarChart3,
        route: '/dashboard/analytics',
        gradient: 'from-indigo-500/20 via-purple-500/10 to-transparent',
        iconBg: 'from-indigo-500 to-purple-600',
        badge: 'Soon',
        activity: 'Financial health score: 72',
        progressLabel: 'Data-driven insights',
    },
    {
        id: 'library',
        title: 'Finance Library',
        description: 'Curated books with summaries, key takeaways and checklists',
        icon: BookOpen,
        route: '/books',
        gradient: 'from-green-500/20 via-emerald-500/10 to-transparent',
        iconBg: 'from-green-500 to-emerald-600',
        activity: '12 books available',
        progressLabel: 'Read & grow',
    },
    {
        id: 'achievements',
        title: 'Achievements',
        description: 'Earn badges and celebrate your financial milestones',
        icon: Trophy,
        route: '/dashboard/achievements',
        gradient: 'from-yellow-500/20 via-amber-500/10 to-transparent',
        iconBg: 'from-yellow-400 to-amber-500',
        badge: 'Soon',
        activity: 'Keep building streaks',
        progressLabel: 'Level up',
    },
    {
        id: 'reports',
        title: 'Reports',
        description: 'Monthly and yearly financial reports with AI commentary',
        icon: FileText,
        route: '/dashboard/reports',
        gradient: 'from-slate-500/20 via-blue-500/10 to-transparent',
        iconBg: 'from-slate-500 to-blue-600',
        badge: 'Soon',
        activity: 'July report ready',
        progressLabel: 'Full picture',
    },
    {
        id: 'profile',
        title: 'Profile',
        description: 'Your financial persona, assessment results and settings',
        icon: User,
        route: '/settings',
        gradient: 'from-pink-500/20 via-rose-500/10 to-transparent',
        iconBg: 'from-pink-500 to-rose-600',
        activity: 'Profile 90% complete',
        progressLabel: 'Your identity',
    },
    {
        id: 'settings',
        title: 'Settings',
        description: 'Account preferences, notifications and privacy controls',
        icon: Settings,
        route: '/settings',
        gradient: 'from-gray-500/20 via-slate-500/10 to-transparent',
        iconBg: 'from-gray-500 to-slate-600',
        activity: 'All systems normal',
        progressLabel: 'Configured',
    },
];
